Feature/image
depromeet/final-team5-server pull request #81
Opened 2021-01-22 07:59 UTC by LeeYuRi1

- image 등록 api 추가
- image 삭제 api 추가
- store 등록, 수정에서 image 필드 삭제
- 테스트 코드 작성

2021-01-23 13:28 UTC, junhaesung requested changes
확인부탁드려요-! 
이미지 업로드/삭제는 로컬에서 테스트하신걸까요? 
개발서버에서도 잘 동작하는지 테스트해봐도좋을거같습니다!

2021-01-23 13:28 UTC, junhaesung commented on domain/src/main/java/com/depromeet/team5/domain/store/Store.java
> +    public void addImage(List<Image> imageList) {
collection 으로 추가할때는 복수형으로 써주는게 좋을거같아요. (addImage's' )

2021-01-23 13:28 UTC, junhaesung commented on domain/src/main/java/com/depromeet/team5/service/impl/StoreServiceImpl.java
> +        List<Image> image = convertImage(imageUploadValues);
복수형으로 쓰면 좋을거같아요 (images )

2021-01-23 13:28 UTC, junhaesung commented on domain/src/main/java/com/depromeet/team5/service/impl/StoreServiceImpl.java
> +        Image image = imageRepository.findById(imageId).orElseThrow(() -> new ImageNotFoundException(imageId));
삭제할 이미지를 찾지 못한경우 에러를 던지기보다 성공으로 좋을거같습니다. 
(이미지가 없는 경우 api 호출 후에 결과적으로 이미지가 삭제된것과 동일하기때문)
멱등성에 대해 알아보면 좋을거같아요 (https://tools.ietf.org/html/rfc7231#section-4.2.2)

2021-01-23 13:28 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/controller/StoreController.java
> +    public ResponseEntity<String> deleteImage(@RequestParam Long imageId) {
`?imageId={}` 형식보다는 `/images/{imageId}` 가 좋을거같아요. 
query parameter 는 get 요청에서 조건을 거는 용도로 많이 사용하고, post, put, delete 에서는 특별한 경우가 아니면 사용하지 않는 것이 좋아요. 지금같은 경우 image 의 식별자에 대해서 delete method 를 호출하는 동작이기때문에 DELETE /images/{imageId} 가 적절합니다.

2021-01-23 13:28 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/controller/StoreController.java
> +    public ResponseEntity<String> saveImage(ImageRequestDto imageRequestDto,
dto 를 통해 store id 를 받는거보다는 uri 에 store id 를 포함하면 좋을거같아요
`POST /stores/{storeId}/images`
이렇게 url 을 설계하면 특정 가게 하위의 Image 를 추가한다는걸 명시적으로 표시할 수 있어요

2021-01-23 14:32 UTC, junhaesung commented on interfaces/src/test/java/com/depromeet/team5/integration/api/StoreTestController.java
> +                .param("image", imageRequestDto.getImage().toString()))
ImageRequestDto 의 image 는 `List<MultipartFile>` 타입인데, toString 으로 입력하게되면 이미지파일이 잘 업로드되지 않을거같아요.

2021-01-26 14:32 UTC, merged

2021-01-29 19:44 UTC, junhaesung reviewed
지난번에 리뷰하면서 놓쳤던 부분있어서 추가했어요!

2021-01-29 19:44 UTC, junhaesung commented on domain/src/main/java/com/depromeet/team5/service/S3FileUploadService.java
> +            log.error("Failed to upload image", e);
upload 는 오타일까요? 
`Failed to delete image` 로 변경된다면, AmazonServiceException 과 SdkClientException 의 처리가 동일해져서 catch 구문을 분리할 필요가 없어보입니다

2021-01-29 19:44 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/controller/StoreController.java
> +    @DeleteMapping("/images/{imageId}")
현재 url 이 `/store/images/{imageId}` 형태인데요
계층구조는 `/stores/{storeId}/images/{imageId}` 가 맞습니다. 
만약 storeId가 필요없다고 판단하셔서 이렇게 path가 작성되었다면, path 를 /store 아래 대신 `/v1/images/{imageId}` 등으로 만드는게 좋을거같아요. 
제 의견은 `POST /stores/{storeId}/images` 로 생성했으니 일관성있게 `DELETE /stores/{storeId}/images/{imageId}` 가 좋을 것 같습니다.

2021-01-29 19:44 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/controller/StoreController.java
> +        return new ResponseEntity<>("image save success", HttpStatus.OK);
API 응답을 작성할 때, 성공했다는 문자열은 큰 의미가 없습니다. 
생성한 리소스의 정보를 표현하거나 (image 객체 등), 리턴할 값이 없다면 204 코드로 응답하고, body 를 차라리 안쓰는게 나을거같아요. 
이미지 등록하는 API 는 서버에 새로 생성된 리소스가 있으니 image 정보를 리턴하면 될 것 같습니다. (imageId, url, createdAt, updatedAt 등)

2021-01-29 19:44 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/controller/StoreController.java
> +                                            @RequestPart(value = "image", required = false) List<MultipartFile> images) {
복수개 업로드하는 기능 굳이 필요한지 잘 모르겠네요. 
클라이언트에서 병렬로 낱개 이미지 여러개를 동시에 업로드하는게 성능상 더 유리하지않을까요?
한 API 로 이미지 여러개를 직렬로 보내야할만큼 동시성 이슈가 문제될거같진 않습니다. 

복수개 업로드시 문제가 되는 부분은 성공/실패여부 판단하기에 애매해서인데요
3개 이미지중 2개 성공하고, 1개만 실패하는 등의 경우일 때 어떤 방식으로 표현해야할지가 정해져있지않아서, 단일이미지만 처리하는것이 좋을거같습니다. 
이 부분은 클라이언트분들도 같이 수정해야하니 백로그로 남겨두고 다음에 같이 논의하면좋을듯해요

2021-01-30 13:06 UTC, LeeYuRi1 commented on domain/src/main/java/com/depromeet/team5/service/S3FileUploadService.java
> +            log.error("Failed to upload image", e);
오타에요!ㅠㅠ AmazonServiceException |  SdkClientException e 이렇게 쓸 경우 AmazonServiceException 이 SdkClientException의 subclass라고 나오는데요 그럼 SdkClientException만 처리를 하면 될까요??

2021-01-30 13:22 UTC, junhaesung commented on domain/src/main/java/com/depromeet/team5/service/S3FileUploadService.java
> +            log.error("Failed to upload image", e);
넵 말씀해주신대로 해주시면될거같아요