가게 정보 추가 및 API 수정
depromeet/final-team5-server pull request #82
Opened 2021-01-23 15:19 UTC by lyle0101

- 가게형식, 결제방식, 출몰시기 필드 추가
- store create, update, detail API 수정
- 다른 PR보다 맨 마지막에 merge 되어야함 (충돌 방지)

2021-01-23 15:20 UTC, lyle0101 commented
테스트

2021-01-23 16:09 UTC, lyle0101 commented
- 로컬에서 테스트 수정하였으나 로그인 토큰 검증 관련 테스트 통과 후 푸시 예정

2021-01-23 16:25 UTC, junhaesung requested changes
확인 부탁드립니다
테스트코드가 없어서, 어떻게 테스트하셨는지도 공유해주시면 좋을거같아요

2021-01-23 16:25 UTC, junhaesung commented on domain/src/main/java/com/depromeet/team5/domain/store/AppearanceDay.java
> +@Data
`@Data` 보다는 꼭 필요한 어노테이션만 추가하는게 좋을거같아요
특히 무의미한 setter 사용은 지양하면 좋을거같습니다. (http://blog.eomdev.com/ddd/2019/08/20/ddd-setter.html)
EqualAndHashCode 메서드 생성할때도 꼭 필요한 필드만 사용하게끔 지정하면 좋을거같아요

2021-01-23 16:25 UTC, junhaesung commented on domain/src/main/java/com/depromeet/team5/domain/store/AppearanceDayType.java
> +public enum AppearanceDayType {
단순히 요일을 나타내는 enum 이라면 `DayOfWeek` 도 고려해보면 좋을 것 같습니다.

2021-01-23 16:25 UTC, junhaesung commented on domain/src/main/java/com/depromeet/team5/domain/store/AppearanceDayType.java
> +    private final String type;
요일을 한글로 나타낸 값인데, type 이라는 이름은 좀 추상적인 것 같습니다. 
값을 유추할 수 있는 구체적인 이름을 사용하면 좋을 것 같습니다.

2021-01-23 16:25 UTC, junhaesung commented on domain/src/main/java/com/depromeet/team5/domain/store/Store.java
> +            store.appearanceDays = new ArrayList<>();
45 라인에서 초기화 했는데, 다시 초기화할 필요가 있을까요?

2021-01-23 16:25 UTC, junhaesung commented on domain/src/main/java/com/depromeet/team5/domain/store/Store.java
> +        if (storeUpdateValue.getAppearanceDays() != null){
코드 정렬해서 올려주세요!
intellij 기본설정이라면 if 등 제어구문 괄호 끝나고 한 칸 띄어쓰는게 맞을거에요

2021-01-23 16:25 UTC, junhaesung commented on domain/src/main/java/com/depromeet/team5/domain/store/Store.java
> +    public void addStoreMenuCategory(StoreMenuCategory storeMenuCategory) {
boolean 에서 void 로 변경하신 이유가 있을까요?

2021-01-23 16:25 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/application/user/UserApplicationService.java
> +            isVerified = kakaoTokenVerifier.isVerified(token);
하위버전 앱에서는 token 을 넣어주지 않아서 비어있을텐데, 이 때 어떻게 동작할까요? 
하위호환을 유지해주어야 할 것 같습니다.

2021-01-23 16:25 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/controller/StoreController.java
> +                        Optional.ofNullable(storeDto.getStoreType()).orElse(StoreType.ROAD),
이렇게하면 사용자가 의도하지 않았는데 `ROAD` 로 설정될 수 있을거같아요.

2021-01-23 16:25 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/dto/StoreDetailDto.java
> +    private StoreType storeType;
외부에 노출하는 dto 에는 되도록 enum 대신 string 을 사용하는 것이 좋습니다. 
client 에서 enum 에 직접 의존하게 되면, 나중에 서버에서 새 enum 종류를 추가했을 때 client 에서 해당 값을 파싱하지 못하는 경우가 생겨서요.

2021-01-23 16:25 UTC, junhaesung commented on interfaces/src/test/java/com/depromeet/team5/integration/UserTest.java
> +        LoginResponse loginDto = userTestController.createTestUser();
타입 변경에 따라 변수명도 같이 변경되면 좋을거같습니다.

2021-01-23 16:25 UTC, junhaesung commented on interfaces/src/test/java/com/depromeet/team5/integration/UserTest.java
> +        LoginResponse loginDto = userTestController.createTestUser();
타입 변경에 따라 변수명도 같이 변경되면 좋을거같습니다.

2021-01-23 16:25 UTC, junhaesung commented on interfaces/src/test/java/com/depromeet/team5/integration/UserTest.java
> +        LoginResponse loginDto = userTestController.createTestUser();
타입 변경에 따라 변수명도 같이 변경되면 좋을거같습니다.

2021-01-23 16:25 UTC, junhaesung commented on interfaces/src/test/java/com/depromeet/team5/integration/UserTest.java
> +        LoginResponse loginDto = userTestController.createTestUser();
타입 변경에 따라 변수명도 같이 변경되면 좋을거같습니다.

2021-01-23 16:25 UTC, junhaesung commented on interfaces/src/test/java/com/depromeet/team5/integration/StoreTest.java
> +        LoginResponse loginDto = userTestController.createTestUser();
타입 변경에 따라 변수명도 같이 변경되면 좋을거같습니다.

2021-01-23 16:25 UTC, junhaesung commented on interfaces/src/test/java/com/depromeet/team5/integration/StoreTest.java
> +        LoginResponse loginDto = userTestController.createTestUser();
타입 변경에 따라 변수명도 같이 변경되면 좋을거같습니다.

2021-01-23 16:25 UTC, junhaesung commented on interfaces/src/test/java/com/depromeet/team5/integration/StoreCategoryTest.java
> +        LoginResponse loginDto = userTestController.createTestUser();
타입 변경에 따라 변수명도 같이 변경되면 좋을거같습니다.

2021-01-23 16:25 UTC, junhaesung commented on interfaces/src/test/java/com/depromeet/team5/integration/SignOutTest.java
> +        LoginResponse loginDto = userTestController.login(userDto);
타입 변경에 따라 변수명도 같이 변경되면 좋을거같습니다.

2021-01-23 16:25 UTC, junhaesung commented on interfaces/src/test/java/com/depromeet/team5/integration/SignOutTest.java
> +        LoginResponse loginDto = this.login( "kakao1", SocialTypes.KAKAO);
타입 변경에 따라 변수명도 같이 변경되면 좋을거같습니다.

2021-01-23 16:25 UTC, junhaesung commented on interfaces/src/test/java/com/depromeet/team5/integration/SignOutTest.java
> +        LoginResponse loginDto = this.login("kakao1", SocialTypes.KAKAO);
타입 변경에 따라 변수명도 같이 변경되면 좋을거같습니다.

2021-01-23 16:25 UTC, junhaesung commented on interfaces/src/test/java/com/depromeet/team5/integration/CategoryTest.java
> +        LoginResponse loginDto = userTestController.createTestUser();
타입 변경에 따라 변수명도 같이 변경되면 좋을거같습니다.

2021-01-23 16:25 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/infrastructure/apple/AppleTokenVerifier.java
> +                && claim.getExpiration().after(new Date());
현재 시간을 사용해야하는경우, 현재시각을 직접 생성하기보다 시간 값을 외부로부터 받아오는 방식이 테스트하기 유리합니다.

2021-01-23 16:25 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/infrastructure/apple/AppleTokenVerifier.java
> +                && claim.getIssuer().equals("https://appleid.apple.com")
getIssuer() 결과는 null 일 수도 있으므로, 이런 경우에는 "https://appleid.apple.com".equals(...) 의 순서로 쓰는 것이 안전합니다

2021-01-23 16:25 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/infrastructure/apple/AppleTokenVerifier.java
> +                 .baseUrl("https://appleid.apple.com")
여러번 사용되는 문자열은 상수로 선언해서 사용해도 좋을 것 같습니다.

2021-01-23 16:25 UTC, junhaesung commented on domain/src/main/java/com/depromeet/team5/domain/store/Store.java
> +        appearanceDays.clear();
요일, 결제방식을 수정할 때 기존값을 모두 삭제하고, 입력된 값을 새로 생성하는 방식으로 구현하신 이유가 있을까요? 
예를 들면, `월화수목금토` 가 입력된 가게가 있다고 할 때, `월화수목금토일` 과 같이 요일 1개를 추가하는 상황에서는
6개 요일에 대해서 delete , 입력된 7개 요일에 대해서 insert  되어서, 요일변경에 대해 총 13개의 쿼리가 생길거같은데 맞을까요? 
기존값과 비교해서 새로 추가된 일요일만 추가한다면 insert 쿼리 1개로 처리할 수 있을 것 같은데요. 
확인 부탁드려요. List 대신 Set 을 사용하는 것도 방법 중 하나일 것 같습니다.

2021-01-23 16:25 UTC, junhaesung commented on domain/src/main/java/com/depromeet/team5/domain/store/Store.java
> +    private List<AppearanceDay> appearanceDays = new ArrayList<>();
현재 가게와 출몰시기 테이블이 1:N 관계인데요. 
출몰시기를 검색조건에서 제외한다면 문제 없을거같긴한데요. 
검색기능이 추가되어서 출몰하는 요일로 검색조건을 잡는다면 어떻게 조회할 수 있을까요?

2021-01-23 16:25 UTC, junhaesung commented on domain/src/main/java/com/depromeet/team5/exception/ApplicationException.java
> +    public ApplicationException() { }
이부분도 괄호 내려쓰는게 intellij 기본 정렬방식에 맞을거에요
intellij 기본값에서 벗어나는 방식으로 컨벤션 변경하고싶다면 유리님이나 저랑 같이 논의해봐도 좋을거같아요

2021-01-23 16:25 UTC, junhaesung commented on domain/src/main/java/com/depromeet/team5/domain/store/PaymentMethodType.java
> +    TRANSFER("계좌이체"),
계좌랑 이체 중에서 하나만 남겨야한다면 계좌가 좀 더 중요해보이는데요
ACCOUNT_TRANSFER 로 쓰는것도 좋을 것 같습니다.

2021-01-25 05:05 UTC, lyle0101 commented on domain/src/main/java/com/depromeet/team5/domain/store/Store.java
> +    private List<AppearanceDay> appearanceDays = new ArrayList<>();
양방향 매핑으로 바꾸어서 출몰시기 쪽에서도 store를 알고 있게 수정했습니다!

2021-01-25 05:08 UTC, lyle0101 commented on domain/src/main/java/com/depromeet/team5/domain/store/Store.java
> +        appearanceDays.clear();
https://blog.leocat.kr/notes/2016/04/26/hibernate-no-longer-reference
위 링크처럼 에러가 나서 해결방법을 보고 적용했고 적용할 때 보니 유리님이 예전에 menu.clear() 사용하신게 보여서 저렇게 작성했는데 다른 방법이 있는지 한번 보겠습니다! Set도 고려해보겠습니다.

2021-01-25 05:19 UTC, lyle0101 commented on domain/src/main/java/com/depromeet/team5/domain/store/Store.java
> +    public void addStoreMenuCategory(StoreMenuCategory storeMenuCategory) {
아 이거는 저 함수가Alt + F7 으로 찾아보니까 StoreServiceImpl 70번째 행에서 한 번 사용되고 있었는데 add 반환값인 boolean이 사용되고 있지 않아서 void로 바꾸었는데, 혹시 다른 목적이 있으셨거나 boolean으로 리턴하는게 더 좋은 코드라고 하시면 다시 고쳐놓겠습니다!

2021-01-25 05:24 UTC, lyle0101 commented on interfaces/src/main/java/com/depromeet/team5/application/user/UserApplicationService.java
> +            isVerified = kakaoTokenVerifier.isVerified(token);
이게 제가 로컬에서 깃을 잘못 써서 PR을 다 섞인채로 올린거의 문제인데요ㅜㅜ 로그인 토큰 검증 관련 새로운 커밋은 이전에 올린 PR에 계속 이어서 올리고 있습니다. 예전에 말씀해주신 부분이라 그쪽에서 토큰이 있는 경우에만 검증하도록 수정했습니다! 다음부터는 깃을 좀 더 잘 쓸 수 있도록 해볼게요ㅜㅜ

2021-01-25 05:40 UTC, lyle0101 commented on interfaces/src/main/java/com/depromeet/team5/dto/StoreDetailDto.java
> +    private StoreType storeType;
String을 사용하는게 나은 이유에 대해서는 이해됬습니다! 그러면 일단 String으로 받은 후에 내부적으로 validation을 하고 옳지 않은 값이 들어오면 400번대 exception을 주는게 맞는 처리인지 궁금합니다!

2021-01-25 05:42 UTC, lyle0101 commented
- 관련 테스트 코드 추가

2021-01-25 06:20 UTC, lyle0101 commented on interfaces/src/main/java/com/depromeet/team5/infrastructure/apple/AppleTokenVerifier.java
> +                && claim.getIssuer().equals("https://appleid.apple.com")
말씀해주신대로 issuer와 audience는 값을 비교하는 순서를 바꿔서 수정했습니다! 혹시 Expiration 같은 경우에도 null 체크를 해야할까요?

2021-01-25 06:21 UTC, lyle0101 commented on interfaces/src/main/java/com/depromeet/team5/infrastructure/apple/AppleTokenVerifier.java
> +                && claim.getExpiration().after(new Date());
저 함수를 호출하는 쪽에서 현재 시간을 넘겨주는 식으로 수정했는데 제가 이해한게 맞을까요?

2021-01-25 15:35 UTC, lyle0101 commented
- 로그인 토큰 검증 관련해서 리뷰해주신 내용은 이전 PR에 올렸습니다.
- ReviewTest에서 delete()는 assertion error가 나고 update()에서는 아예 exception이 발생하는 이슈가 있음.

2021-01-27 13:18 UTC, merged