feat: distance 이내의 가게들을 조회하는 api 추가
depromeet/final-team5-server pull request #99
Opened 2021-02-25 19:05 UTC by LeeYuRi1

2021-02-26 14:05 UTC, junhaesung requested changes
api 를 새로 만드는것보단 /api/v1/stores api 에 필요한 기능 (내위치로부터 거리계산) 하는 기능을 추가하는게 더 좋을거같아요. 
테스트케이스도 추가하면 좋을 것 같습니다.

2021-02-26 14:05 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/controller/StoreController.java
> +    @GetMapping("/getStoresByDistance")
resource 를 나타낼 수 있는 path 로 정하면 좋을거같습니다. 
http://slides.com/eungjun/rest#/

2021-02-26 14:05 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/controller/StoreController.java
> +    @GetMapping("/getStoresByDistance")
비슷한 기능을 하는 api 를 여러개 유지하는 것 보다는 `/api/v1/stores` api 에 거리 관련 기능을 추가하는게 더 좋을 것 같습니다.

2021-02-27 18:26 UTC, LeeYuRi1 commented on interfaces/src/main/java/com/depromeet/team5/controller/StoreController.java
> +    @GetMapping("/getStoresByDistance")
수정했습니다! 근데 /api/v1/store랑 /api/v1/stores랑은 뭐가 다른건가요??

2021-02-28 08:22 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/controller/StoreController.java
> +                                                                   @RequestParam(required = false) Double mapLatitude,
배포된 앱에서 사용중인 api 아니니까 optional 로 만들지 않아도될거같아요

2021-02-28 08:22 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/dto/StoreResponse.java
> +    private List<CategoryType> categories;
외부로 응답할때 enum 보다는 string 으로 쓰는게 좋을거같아요
파싱하는쪽에서 enum 개수를 미리 갖고있으면, 서버에서 먼저 필드를 추가할 수 없어서요

2021-02-28 08:22 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/application/store/StoreAssembler.java
> +        storeResponse.setRating(Optional.ofNullable(store.getRating()).orElse(0f));
응답모델을 만들 때 null 검사하는건 의미가 없을거같아요
rating 값을 만드는 곳에서 null 이 들어오지 않도록 validation 을 추가하고, 응답하는 곳에서는 rating 값 그대로 내려주는게 좋을 것 같습니다.

2021-02-28 08:22 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/application/store/StoreAssembler.java
> +        storeResponse.setRating(Optional.ofNullable(store.getRating()).orElse(0f));
이전에 가게 추가/수정 rating 값 채우는 코드가 누락되어서 null 인 값이 일부 존재했었고, 
지금은 해당 버그 수정된 상태라 rating 이 null 이면 안되는 상황입니다

2021-02-28 08:23 UTC, junhaesung commented
테스트 헬퍼 코드는 작성해주신거 확인헀는데, 그 코드 활용해서 직접 테스트하는 코드는 아직 없는거같네요

2021-02-28 18:29 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/controller/StoreController.java
> +                                                                   @RequestParam Double distance) {
현재 api 응답에서 거리 나타낼때는 미터 단위로 쓰고있는데요
요청할때만 km 로 단위 쓰는게 어색한거같아요. 
2km 이면 2000 으로 받는건 어떨까요?

2021-03-01 08:04 UTC, junhaesung commented on interfaces/src/main/java/com/depromeet/team5/controller/StoreController.java
> +    @GetMapping("/getStoresByDistance")
보통 컬렉션을 나타낼때는 복수명사를 사용해서 stores 도 사용가능하게 추가했어요
store 는 deprecated 할 예정입니다

2021-03-01 08:04 UTC, merged